### ISSUE TITLE
check number of pages of example-image-duck.pdf

### ISSUE THREAD

**Issue by u-fischer** [Skillmon/ltx_duckuments#1]
Imho it would be sensible to check the number of pages of example-image-duck.pdf (for the random numbers) in case someone create a local file. This can be done with pdflatex with `\pdfximage`
  `\the\pdflastximagepages`. In luatex the commands are named `\saveimageresource` and `\lastsavedimageresourcepages`.

**Comment by Skillmon** [comment]
That sounds reasonable, @u-fischer. Thanks for the suggestion. Do you by chance know a way of doing this in XeTeX? Currently the package doesn't load in XeTeX, but the only reason is that XeTeX doesn't support `\int_rand:nn`. So the options would be to either always use the first page in XeTeX, or use a different random integer macro (perhaps `tikz`, which is too big just for that purpose, or `lcg`). Then the package would be XeTeX compatible.

**Comment by u-fischer** [comment]
For xetex:

~~~~~
\documentclass{article}

\begin{document}

\the\XeTeXpdfpagecount "example-image-a4-numbered.pdf"

\end{document}
~~~~~

Regarding the random pages: They don't need to be really random. You could simply add e.g. the \day and/or  \month.

**Comment by Skillmon** [comment]
@u-fischer thanks again. I went and implemented an RC4 pseudo-random generator (for procrastinating reasons) for XeTeX-usage.
